name: Deploy Next.js Static Site to Production

on:
  push:
    branches:
      - master

jobs:
  Deploy-Frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          npm run build || { echo "Build failed"; exit 1; }
          ls -la out || echo "out directory does not exist"
          ls -la out/* || echo "No files in out directory"

      - name: Deploy Static Site
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.MAIN_FRONT_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: ftps
          local-dir: ./out/
          server-dir: /
          dry-run: false
          log-level: verbose
          dangerous-clean-slate: false
          exclude: |
            .github/**
            **/.git/**
            **/.gitignore
            **/.env
            **/.env.*
            **/next.config.js
            **/package.json
            **/package-lock.json
            **/node_modules/**
            **/public/**
            **/src/**
            **/.next/**
            **/*.map
            **/tsconfig.json
            **/README.md
            **/LICENSE
            **/lib/**

      - name: Verify Deployment
        run: |
          curl -f "http://${{ secrets.MAIN_DOMAIN }}" || exit 1