name: Deploy Next.js to Production (Node.js Server)

on:
  push:
    branches:
      - master

jobs:
  Deploy-Frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          npm run build || { echo "Build failed"; exit 1; }
          ls -la .next || echo ".next directory does not exist"
          ls -la package.json || echo "package.json does not exist"

      - name: Transfer Files to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: ".next/,package.json,package-lock.json"
          target: /home/u688499170/domains/eastendagro.com/public_html/frontend
          strip_components: 1

      - name: Start Application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            export PATH=$PATH:/usr/local/bin:/usr/bin:/bin
            cd /home/u688499170/domains/eastendagro.com/public_html/frontend
            npm ci || { echo "npm ci failed"; exit 1; }
            npm install pm2 --no-save || { echo "pm2 install failed"; exit 1; }
            npx pm2 restart next-app || npx pm2 start npm --name "next-app" -- start -- -p 3000

      - name: Verify Deployment
        run: |
          curl -f "http://${{ secrets.MAIN_DOMAIN }}" || exit 1