name: Deploy Next.js to Production (Node.js Server)

on:
  push:
    branches:
      - master

jobs:
  Deploy-Frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        env:
          NODE_ENV: production
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to deployment directory
            cd /path/to/your/app
            # Pull latest code (assuming repo is cloned on server)
            git pull origin master
            # Install dependencies
            npm ci
            # Copy build artifacts
            rm -rf .next
            mv ${{ github.workspace }}/.next .
            # Restart server (e.g., using PM2)
            pm2 restart next-app

      - name: Verify Deployment
        run: |
          curl -f "http://${{ secrets.MAIN_DOMAIN }}" || exit 1